name: ci

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  # required to login to AWS via OIDC.
  id-token: write
  contents: read
  # required to trigger deploy workflow.
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ... build app ...

  deploy:
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    name: Deploy to dev ${{ github.ref != 'refs/heads/main' && 'pr-${{ github.event.pull_request.number }}' }}
    needs: [build-and-push]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      suffix: ${{ github.ref == 'refs/heads/main' && '' || 'pr-${{ github.event.pull_request.number }}' }}
