name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  # required to login to AWS via OIDC.
  id-token: write
  contents: read
  # required to trigger deploy workflow.
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ... build app ...
      - name: Trigger "Deploy to dev" workflow
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run --repo ${{ github.repository }} deploy.yml -r ${{ github.ref }} -f environment=dev

      - name: Trigger "Deploy to dev for PR - ${{ github.event.pull_request.title }}" workflow
        if: github.base_ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run --repo ${{ github.repository }} deploy.yml -r ${{ github.ref }} -f environment=dev -f suffix=${{ github.base_ref#refs/heads/ }}
